package model;
// Generated 09-mar-2018 12:34:10 by Hibernate Tools 4.3.1
import java.util.*;
import javax.persistence.*;
import static javax.persistence.GenerationType.IDENTITY;
import org.hibernate.Session;

/**TblPuestos generated by hbm2java */
@Entity
@Table(name = "tbl_Puestos")
public class TblPuestos implements java.io.Serializable, Crud {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Puesto_Id", unique = true, nullable = false)
    private Integer puestoId;

    @Column(name = "Puesto_Nombre")
    private String puestoNombre;

//    @OneToMany(targetEntity = TblEmpleados.class, fetch = FetchType.LAZY, mappedBy = "tblPuestos")
//    private Set tblEmpleadoses = new HashSet(0);

    public TblPuestos() {
    }

    public TblPuestos(String puestoNombre, Set tblEmpleadoses) {
        this.puestoNombre = puestoNombre;
//        this.tblEmpleadoses = tblEmpleadoses;
    }

    public Integer getPuestoId() {
        return this.puestoId;
    }

    public void setPuestoId(Integer puestoId) {
        this.puestoId = puestoId;
    }

    public String getPuestoNombre() {
        return this.puestoNombre;
    }

    public void setPuestoNombre(String puestoNombre) {
        this.puestoNombre = puestoNombre;
    }

//    public Set getTblEmpleadoses() {
//        return this.tblEmpleadoses;
//    }
//
//    public void setTblEmpleadoses(Set tblEmpleadoses) {
//        this.tblEmpleadoses = tblEmpleadoses;
//    }

    @Override
    public int hashCode() {
        return puestoId.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        Integer puestoid = ((TblPuestos) obj).getPuestoId();
        return Objects.equals(puestoId, puestoid);
    }

    public static List<TblPuestos> selectAll() {
        Session sesion = HibernateHelper.getSessionFactory().openSession();
        sesion.getTransaction().begin();
        List<TblPuestos> lista = sesion.createQuery("from TblPuestos").list();
        sesion.getTransaction().commit(); 
        return lista;
    }
    
    public static TblPuestos buscarxClave(Integer Id){
        Session sesion=HibernateHelper.getSessionFactory().openSession();
        TblPuestos puesto=sesion.get(TblPuestos.class, Id);
        sesion.close();
        return puesto;
    }

    @Override
    public void insert() {
        Session sesion = HibernateHelper.getSessionFactory().openSession();
        sesion.getTransaction().begin();
        sesion.saveOrUpdate(this);
        sesion.getTransaction().commit();
    }

    @Override
    public void delete() {
        Session sesion = HibernateHelper.getSessionFactory().openSession();
        sesion.getTransaction().begin();        
        sesion.delete(this);
        sesion.getTransaction().commit();
    }

}